# Home Assistant configuration

# Loads default set of integrations. Do not remove.
default_config:

# Keep your regular includes if you use them
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Note: HTTP reverse proxy settings are appended at runtime by the container
# if missing in the persistent /config/configuration.yaml volume.
